export const ALPHABET = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
];

export const WORD_LIST = {
  developerVocabulary1: [
    "JavaScript",
    "HTML",
    "CSS",
    "Node.js",
    "React",
    "Angular",
    "Vue.js",
    "Express",
    "MongoDB",
    "SQL",
    "Git",
    "GitHub",
    "REST API",
    "JSON",
    "AJAX",
    "Callback",
    "Promise",
    "Async/Await",
    "ES6",
    "Webpack",
  ],

  developerVocabulary2: [
    "Babel",
    "NPM",
    "Yarn",
    "Responsive Design",
    "API",
    "Frontend",
    "Backend",
    "Database",
    "Scalability",
    "Agile",
    "Scrum",
    "Kanban",
    "CI/CD",
    "Testing",
    "Debugging",
    "Responsive Design",
    "Cross-browser Compatibility",
    "UI/UX",
    "Responsive Web Design",
    "Docker",
  ],

  developerVocabulary3: [
    "Microservices",
    "Authentication",
    "Authorization",
    "JWT",
    "OAuth",
    "DevOps",
    "Serverless",
    "Full Stack",
    "MVC",
    "Observer Pattern",
    "Singleton Pattern",
    "Factory Pattern",
    "Proxy Pattern",
    "Decorator Pattern",
    "Observer Pattern",
    "Immutable",
    "Functional Programming",
    "Design Patterns",
    "RESTful",
    "GraphQL",
  ],

  developerVocabulary4: [
    "WebSocket",
    "WebAssembly",
    "Progressive Web App (PWA)",
    "Single Page Application (SPA)",
    "SEO",
    "CORS",
    "Middleware",
    "Session",
    "Cookie",
    "OAuth",
    "JWT",
    "OAuth2",
    "GraphQL",
    "WebSockets",
    "WebAssembly",
    "Responsive Design",
    "Cross-browser Compatibility",
    "Progressive Web App (PWA)",
    "Single Page Application (SPA)",
    "SEO",
    "CORS",
    "Middleware",
    "Session",
    "Cookie",
  ],
  ingenieroVocabulario1: [
    "Engineer",
    "Mechanical",
    "Civil",
    "Electrical",
    "Software",
    "Hardware",
    "Robotics",
    "Aerospace",
    "Structural",
    "Materials",
    "Thermodynamics",
    "Control Systems",
    "Finite Element Analysis",
    "CAD (Computer-Aided Design)",
    "CAM (Computer-Aided Manufacturing)",
    "PLC (Programmable Logic Controller)",
    "Automation",
    "Machine Learning",
    "Data Structures",
    "Algorithm",
    "Circuit",
    "Network",
  ],
  ingenieroVocabulario2: [
    "Prototype",
    "Simulation",
    "Optimization",
    "Project Management",
    "Fluid Dynamics",
    "Heat Transfer",
    "Voltage",
    "Current",
    "Resistance",
    "Voltage Drop",
    "Power Factor",
    "Renewable Energy",
    "Geotechnical",
    "Hydraulics",
    "Pneumatics",
    "Instrumentation",
    "Telecommunications",
    "Signal Processing",
    "Quality Control",
    "Risk Assessment",
    "Sustainability",
    "Ethics in Engineering",
  ],
  vocabularioIngles1: [
    "the",
    "be",
    "to",
    "of",
    "and",
    "a",
    "in",
    "that",
    "have",
    "I",
    "it",
    "for",
    "not",
    "on",
    "with",
    "he",
    "as",
    "you",
    "do",
    "at",
    "this",
    "but",
    "his",
    "by",
    "from",
  ],
  vocabularioIngles2: [
    "they",
    "we",
    "say",
    "her",
    "she",
    "or",
    "an",
    "will",
    "my",
    "one",
    "all",
    "would",
    "there",
    "their",
    "what",
    "so",
    "up",
    "out",
    "if",
    "about",
    "who",
    "get",
    "which",
    "go",
    "me",
    "when",
  ],
};
